// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: expression.proto

package proto_expr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Protosh_Run_FullMethodName = "/proto_expr.Protosh/Run"
)

// ProtoshClient is the client API for Protosh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoshClient interface {
	Run(ctx context.Context, in *ScriptDescriptor, opts ...grpc.CallOption) (*Data, error)
}

type protoshClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoshClient(cc grpc.ClientConnInterface) ProtoshClient {
	return &protoshClient{cc}
}

func (c *protoshClient) Run(ctx context.Context, in *ScriptDescriptor, opts ...grpc.CallOption) (*Data, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Data)
	err := c.cc.Invoke(ctx, Protosh_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoshServer is the server API for Protosh service.
// All implementations must embed UnimplementedProtoshServer
// for forward compatibility.
type ProtoshServer interface {
	Run(context.Context, *ScriptDescriptor) (*Data, error)
	mustEmbedUnimplementedProtoshServer()
}

// UnimplementedProtoshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoshServer struct{}

func (UnimplementedProtoshServer) Run(context.Context, *ScriptDescriptor) (*Data, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedProtoshServer) mustEmbedUnimplementedProtoshServer() {}
func (UnimplementedProtoshServer) testEmbeddedByValue()                 {}

// UnsafeProtoshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoshServer will
// result in compilation errors.
type UnsafeProtoshServer interface {
	mustEmbedUnimplementedProtoshServer()
}

func RegisterProtoshServer(s grpc.ServiceRegistrar, srv ProtoshServer) {
	// If the following call panics, it indicates UnimplementedProtoshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Protosh_ServiceDesc, srv)
}

func _Protosh_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScriptDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoshServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Protosh_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoshServer).Run(ctx, req.(*ScriptDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

// Protosh_ServiceDesc is the grpc.ServiceDesc for Protosh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Protosh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_expr.Protosh",
	HandlerType: (*ProtoshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Protosh_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expression.proto",
}
