// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: expression.proto

package proto_expr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Encoding:
	//
	//	*Data_Text
	//	*Data_Binary
	Encoding      isData_Encoding `protobuf_oneof:"encoding"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_expression_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Data) GetEncoding() isData_Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *Data) GetText() string {
	if x != nil {
		if x, ok := x.Encoding.(*Data_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Data) GetBinary() []byte {
	if x != nil {
		if x, ok := x.Encoding.(*Data_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isData_Encoding interface {
	isData_Encoding()
}

type Data_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Data_Binary struct {
	Binary []byte `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

func (*Data_Text) isData_Encoding() {}

func (*Data_Binary) isData_Encoding() {}

// These are S-Expressions / AST for a basic LISP and interpreter
// Interpret Cells as dispatch, otherwise merely flatten the expression and keep going
// This structure allows for Dispatch "pipelining" eg f1 (f2 (f3 a))
// But because of its tree-like structure it also gives us higher order functions eg ((f1 f2) f3) a
type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Expression_Str
	//	*Expression_Uri
	//	*Expression_Data
	//	*Expression_Cell_
	Content       isExpression_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_expression_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{1}
}

func (x *Expression) GetContent() isExpression_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Expression) GetStr() string {
	if x != nil {
		if x, ok := x.Content.(*Expression_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Expression) GetUri() string {
	if x != nil {
		if x, ok := x.Content.(*Expression_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *Expression) GetData() *Data {
	if x != nil {
		if x, ok := x.Content.(*Expression_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Expression) GetCell() *Expression_Cell {
	if x != nil {
		if x, ok := x.Content.(*Expression_Cell_); ok {
			return x.Cell
		}
	}
	return nil
}

type isExpression_Content interface {
	isExpression_Content()
}

type Expression_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Expression_Uri struct {
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3,oneof"`
}

type Expression_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Expression_Cell_ struct {
	Cell *Expression_Cell `protobuf:"bytes,4,opt,name=cell,proto3,oneof"`
}

func (*Expression_Str) isExpression_Content() {}

func (*Expression_Uri) isExpression_Content() {}

func (*Expression_Data) isExpression_Content() {}

func (*Expression_Cell_) isExpression_Content() {}

// from proto-type:
// In addition to deferred computation this gives us the ability to represent the Builder Pattern
// As long as method's input and output_types are the same, it means we can essentially convert Dispatch[] / stream Dispatch into x.MethodA().MethodB()
// When those types are FileDescriptorProto, it essentially allows us to have a type system closed under f: FileDescriptorProto x f -> FileDescriptorProto
// So, Dispatch(Fn FileDescriptorProto -> X) is sufficient for any transformation across types, or evaluating to any other expression.
// from proto-expr:
// don't encode MethodDescriptorProto, just its uri
type DispatchRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uri   string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// Validate that the input type of uri is the same as request's type
	Request       *Data `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRPC) Reset() {
	*x = DispatchRPC{}
	mi := &file_expression_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRPC) ProtoMessage() {}

func (x *DispatchRPC) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRPC.ProtoReflect.Descriptor instead.
func (*DispatchRPC) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchRPC) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DispatchRPC) GetRequest() *Data {
	if x != nil {
		return x.Request
	}
	return nil
}

type Expression_Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lhs           *Expression            `protobuf:"bytes,1,opt,name=lhs,proto3" json:"lhs,omitempty"`
	Rhs           *Expression            `protobuf:"bytes,2,opt,name=rhs,proto3" json:"rhs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression_Cell) Reset() {
	*x = Expression_Cell{}
	mi := &file_expression_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression_Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression_Cell) ProtoMessage() {}

func (x *Expression_Cell) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression_Cell.ProtoReflect.Descriptor instead.
func (*Expression_Cell) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Expression_Cell) GetLhs() *Expression {
	if x != nil {
		return x.Lhs
	}
	return nil
}

func (x *Expression_Cell) GetRhs() *Expression {
	if x != nil {
		return x.Rhs
	}
	return nil
}

var File_expression_proto protoreflect.FileDescriptor

const file_expression_proto_rawDesc = "" +
	"\n" +
	"\x10expression.proto\x12\n" +
	"proto_expr\"V\n" +
	"\x04Data\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06binary\x18\x03 \x01(\fH\x00R\x06binaryB\n" +
	"\n" +
	"\bencoding\"\xf6\x01\n" +
	"\n" +
	"Expression\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x12\n" +
	"\x03uri\x18\x02 \x01(\tH\x00R\x03uri\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto_expr.DataH\x00R\x04data\x121\n" +
	"\x04cell\x18\x04 \x01(\v2\x1b.proto_expr.Expression.CellH\x00R\x04cell\x1aZ\n" +
	"\x04Cell\x12(\n" +
	"\x03lhs\x18\x01 \x01(\v2\x16.proto_expr.ExpressionR\x03lhs\x12(\n" +
	"\x03rhs\x18\x02 \x01(\v2\x16.proto_expr.ExpressionR\x03rhsB\t\n" +
	"\acontent\"K\n" +
	"\vDispatchRPC\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12*\n" +
	"\arequest\x18\x02 \x01(\v2\x10.proto_expr.DataR\arequestB#Z!github.com/accretional/proto-exprb\x06proto3"

var (
	file_expression_proto_rawDescOnce sync.Once
	file_expression_proto_rawDescData []byte
)

func file_expression_proto_rawDescGZIP() []byte {
	file_expression_proto_rawDescOnce.Do(func() {
		file_expression_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expression_proto_rawDesc), len(file_expression_proto_rawDesc)))
	})
	return file_expression_proto_rawDescData
}

var file_expression_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_expression_proto_goTypes = []any{
	(*Data)(nil),            // 0: proto_expr.Data
	(*Expression)(nil),      // 1: proto_expr.Expression
	(*DispatchRPC)(nil),     // 2: proto_expr.DispatchRPC
	(*Expression_Cell)(nil), // 3: proto_expr.Expression.Cell
}
var file_expression_proto_depIdxs = []int32{
	0, // 0: proto_expr.Expression.data:type_name -> proto_expr.Data
	3, // 1: proto_expr.Expression.cell:type_name -> proto_expr.Expression.Cell
	0, // 2: proto_expr.DispatchRPC.request:type_name -> proto_expr.Data
	1, // 3: proto_expr.Expression.Cell.lhs:type_name -> proto_expr.Expression
	1, // 4: proto_expr.Expression.Cell.rhs:type_name -> proto_expr.Expression
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_expression_proto_init() }
func file_expression_proto_init() {
	if File_expression_proto != nil {
		return
	}
	file_expression_proto_msgTypes[0].OneofWrappers = []any{
		(*Data_Text)(nil),
		(*Data_Binary)(nil),
	}
	file_expression_proto_msgTypes[1].OneofWrappers = []any{
		(*Expression_Str)(nil),
		(*Expression_Uri)(nil),
		(*Expression_Data)(nil),
		(*Expression_Cell_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expression_proto_rawDesc), len(file_expression_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expression_proto_goTypes,
		DependencyIndexes: file_expression_proto_depIdxs,
		MessageInfos:      file_expression_proto_msgTypes,
	}.Build()
	File_expression_proto = out.File
	file_expression_proto_goTypes = nil
	file_expression_proto_depIdxs = nil
}
